name: FastAPI CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (dev)
        run: uv sync --group dev

      # -----------------
      # Code Quality
      # -----------------
      - name: Ruff (lint)
        run: uv run ruff check .

      - name: MyPy (types)
        run: uv run mypy app

      # -----------------
      # Security
      # -----------------
      - name: Bandit (security scan)
        run: uv run bandit -r app

      - name: Dependency audit
        run: uv run pip-audit

      # -----------------
      # Tests
      # -----------------
      - name: Pytest
        run: uv run pytest
